# Generated by Django 3.2.18 on 2023-04-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('img1', models.ImageField(blank=True, null=True, upload_to='slider/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='slider/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='slider/')),
            ],
        ),
    ]
