# Generated by Django 3.2.18 on 2023-04-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='text',
        ),
    ]
