# Generated by Django 3.2.18 on 2023-04-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='featured',
        ),
        migrations.AddField(
            model_name='slider',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
    ]
