# Generated by Django 3.2.18 on 2023-04-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midimg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='midimg/')),
            ],
        ),
    ]
