# Generated by Django 3.2.18 on 2023-04-08 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_app', '0002_midimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='midimg',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='midimg',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
