# Generated by Django 3.2.18 on 2023-04-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_app', '0002_auto_20230407_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='img',
            new_name='featured',
        ),
    ]
