# Generated by Django 3.2.18 on 2023-04-06 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_app', '0003_auto_20230406_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='slider',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
