# Generated by Django 3.2.18 on 2023-04-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_app', '0003_auto_20230408_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Midimg',
        ),
    ]
