# Generated by Django 3.2.18 on 2023-04-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_app', '0003_rename_img_slider_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='featured',
            new_name='img',
        ),
    ]
