# Generated by Django 3.2.18 on 2023-04-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_app', '0004_rename_featured_slider_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
