# Generated by Django 3.2.18 on 2023-04-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_app', '0005_auto_20230406_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='slider1/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='slider2/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='slider3/'),
        ),
    ]
