# Generated by Django 3.2.18 on 2023-04-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_app', '0006_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='subcategory',
        ),
    ]
