# Generated by Django 3.2.18 on 2023-04-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_app', '0007_auto_20230406_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='subtitle1',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='subtitle2',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='subtitle3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title3',
        ),
        migrations.AddField(
            model_name='slider',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
