# Generated by Django 3.2.18 on 2023-04-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_app', '0008_auto_20230406_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='created_date',
        ),
    ]
