# Generated by Django 3.2.18 on 2023-04-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_app', '0010_slider_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='img',
        ),
        migrations.AddField(
            model_name='slider',
            name='featured',
            field=models.ImageField(blank=True, null=True, upload_to='featured/'),
        ),
    ]
