# Generated by Django 3.2.18 on 2023-04-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_app', '0011_auto_20230407_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
